/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

/**
 *
 * @author Utente
 */
public class RicettarioUI extends javax.swing.JFrame {

    /**
     * Creates new form RicettarioUI
     */
    public RicettarioUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonPrimiPiatti = new javax.swing.JButton();
        jButtonSecondiPiatti = new javax.swing.JButton();
        jButtonContorni = new javax.swing.JButton();
        jButtonFrutta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonReport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jButtonPrimiPiatti.setBackground(new java.awt.Color(255, 102, 0));
        jButtonPrimiPiatti.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonPrimiPiatti.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPrimiPiatti.setText("Primi Piatti");

        jButtonSecondiPiatti.setBackground(new java.awt.Color(255, 102, 0));
        jButtonSecondiPiatti.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonSecondiPiatti.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSecondiPiatti.setText("Secondi Piatti");

        jButtonContorni.setBackground(new java.awt.Color(255, 102, 0));
        jButtonContorni.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonContorni.setForeground(new java.awt.Color(255, 255, 255));
        jButtonContorni.setText("Contorni");

        jButtonFrutta.setBackground(new java.awt.Color(255, 102, 0));
        jButtonFrutta.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonFrutta.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFrutta.setText("Frutta e dessert");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Creazione Menù");

        jButtonReport.setBackground(new java.awt.Color(255, 102, 0));
        jButtonReport.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonReport.setForeground(new java.awt.Color(255, 255, 255));
        jButtonReport.setText("Report");
        jButtonReport.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonReport))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonFrutta)
                    .addComponent(jButtonContorni)
                    .addComponent(jButtonSecondiPiatti)
                    .addComponent(jButtonPrimiPiatti))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabel1)
                .addContainerGap(175, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(jButtonPrimiPiatti)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSecondiPiatti)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonContorni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonFrutta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(jButtonReport))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RicettarioUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RicettarioUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RicettarioUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RicettarioUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RicettarioUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonContorni;
    private javax.swing.JButton jButtonFrutta;
    private javax.swing.JButton jButtonPrimiPiatti;
    private javax.swing.JButton jButtonReport;
    private javax.swing.JButton jButtonSecondiPiatti;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
